[providers]
php = true

[phases.setup]
nixPkgs = [
    "php81", 
    "php81Packages.composer",
    "php81Extensions.pdo_sqlite",
    "php81Extensions.mbstring",
    "php81Extensions.gd",
    "php81Extensions.xml",
    "php81Extensions.bcmath",
    "php81Extensions.ctype"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan key:generate --force",
    "touch database/database.sqlite",
    "php artisan migrate --force --seed"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
