<?php

return array (
  'site_name' => 'المحافظة العقارية - أولاد جلال',
  'site_url' => 'http://127.0.0.1:8000',
  'site_description' => 'نظام متكامل لإدارة الأراضي والملكيات العقارية',
  'site_keywords' => 'محافظة عقارية, أولاد جلال, شهادة سلبية',
  'contact_email' => 'info@conservation.dz',
  'contact_phone' => '+213 XXX XXX XXX',
  'contact_fax' => NULL,
  'emergency_phone' => NULL,
  'contact_address' => 'أولاد جلال، الجزائر',
  'working_hours' => 'من السبت إلى الخميس: 8:00 صباحاً - 4:00 مساءً',
  'gps_longitude' => NULL,
  'gps_latitude' => NULL,
  'mail_host' => 'smtp.gmail.com',
  'mail_port' => '587',
  'mail_username' => 'your-email@gmail.com',
  'mail_password' => NULL,
  'mail_from_address' => 'your-email@gmail.com',
  'mail_from_name' => 'المحافظة العقارية',
  'mail_encryption' => 'tls',
  'site_active' => true,
  'allow_registration' => true,
  'daily_request_limit' => '5',
  'per_page' => '20',
  'primary_color' => '#1a5632',
  'secondary_color' => '#c9a063',
  'session_lifetime' => '120',
  'max_file_size' => '5',
  'social_facebook' => NULL,
  'social_twitter' => NULL,
  'social_instagram' => NULL,
  'social_linkedin' => NULL,
  'social_youtube' => NULL,
  'social_whatsapp' => NULL,
  'notify_new_requests' => true,
  'sms_notifications' => true,
  'notify_certificate_ready' => '1',
  'admin_notification_email' => 'admin@conservation.dz',
  'daily_stats_report' => 'daily',
  'report_time' => '08:00',
  'min_password_length' => '8',
  'max_login_attempts' => '5',
  'backup_frequency' => 'daily',
);
